spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ainannan?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # json格式化，日期格式化，时间加8小时。
  jackson:
    #date-format: yyyy-MM-dd
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      
  redis:
    host: localhost
    port: 6379
    password: newheyd123321
#server: 
#  context-path: /ann  
   
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  type-aliases-package: cn.ainannan

logging: 
  level:
    org.springframework.web: info
    # org.mybatis: debug

myPic-basePath: H:\尚羊羊\图片\个人相册\
ecxel-basePath: H:\尚羊羊\个人文档\excel\

#spring.resources.static-locations: file:H:\尚羊羊\图片\个人相册\
#spring.mvc.static-path-pattern: /**