pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  reasonable: true
server:
  port: 8001
  servlet:
    context-path: /
    session:
      timeout: 1800
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ainannan?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.20.0.55:3306/dv_db_original?useUnicode=true&characterEncoding=utf8
#    username: jns_canlian
#    password: 123456aA?
#    driver-class-name: com.mysql.jdbc.Driver
    
  # json格式化，日期格式化，时间加8小时。
  jackson:
    #date-format: yyyy-MM-dd
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  session:
    store-type: none
    redis:
      flush-mode: immediate
    timeout: 7200

  redis:
    host: localhost
    port: 6379
    password: newheyd123321
#server: 
#  context-path: /ann  

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  type-aliases-package: cn.ainannan

logging: 
  level:
    org.springframework.web: info
    org.mybatis: debug

myPanfu: 'H:'

myPic-basePath: '\尚羊羊\图片\个人相册\'
#myPic-basePath: '\尚羊羊\图片\金馆长\source\'
ecxel-basePath: '\尚羊羊\个人文档\excel\'

#spring.resources.static-locations: file:H:\尚羊羊\图片\个人相册\
#spring.mvc.static-path-pattern: /**