package com.newheyd.base.util;

public class RSA3rdEncUtil {

    private static final String PRIVATE_KEY = "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIRQeDSr8yqr90-f8_ukV8WrGD185TNZ-wUJpkrLqk9ZbpZpwvPAg-axUOVc2ISt0FRA4szXrdd-J0WRofAK4Bc1lpCI9Zs8wvOh4JphtmwRyJfQqVm14lXiohIAlzX0NHW68RaXNvYQ3a6sFzWhpqtSPKIyLJUmcO0_2kzwPJKJAgMBAAECgYAnrAD-uffE-Z7DbxA2iUYP7IbuGL6YMQiEsCn-DybXd9cinj9n2ncx-kRpIPeCgKMQQAxAowJqtFaOE2ZclMYvfZaWLjeon6GOIcS2wekLtg808HSLI_DOzuyJmclEspPjhDN9FOoBpnNmxuQQwse1iifE2z9IdUoZIeVz7zPgIQJBAOtiNdezJI-c4ZvNxTvj912GSTsngulv_kGajbcL7XvA8SOCzU_yPhsNCCiMxNADXeRSMhgHZ97cLQDoJHBPyp0CQQCP5ztI1FBiIZeEbx20nIZhuk7L_znHayQergifExSfAabuoIgRbC-hHpFg7W6RK1Yo7bUweS9oo4uWOdB5XH3dAkALx86KDR03UtK3yYSlirNGqwHfRAr5Q_GltuaA0sf_-ZgX_uPnrGgPUoel_-WZw5Ffa_211ikMrlhSQ0wPku7BAkA20_lIlGxUF0xtjxCYYhLpZVzkaMgQ7QeEEPcD9PckZjK-NLfjO38iOk1VyuEXupVHXtpsL6AalEV45WpC8zSZAkEA4OT2bn6DiZeZ2JAQVpI9n4WCWa_V4ndH0Ei5_QdofRRmxeuGkv6js-AtjatBsjSz6RLQ6MOCTlrZbiFa35ujOw";

    public static String encrypt(String input) {
        return com.newheyd.base.util.RSAUtil.encrypt(input, PRIVATE_KEY);
    }

}
